name: Core CI - Build, Test, Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    name: Haskell Build, Test & Lint
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up GHC and Cabal
        uses: haskell/actions/setup@v2
        with:
          ghc-version: '9.2.8'
          cabal-version: '3.8'

      - name: Cache Haskell dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cabal/store
          key: ${{ runner.os }}-ghc-${{ hashFiles('**/*.cabal') }}

      - name: Build project dependencies
        run: cabal build --only-dependencies --enable-tests all

      - name: Build ULF project
        run: cabal build --enable-tests all

      - name: Run ULF unit tests
        run: cabal test all
